In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [24]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential



In [39]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [40]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 2)                 6         
                                                                 
 dense_8 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [41]:
model.get_weights()

[array([[ 0.7699636 , -0.7769334 ],
        [ 0.67732537, -0.9503802 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.147447 ],
        [-0.9798997]], dtype=float32),
 array([0.], dtype=float32)]

In [42]:
import numpy as np

initialized_weights = [
    np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
    np.array([0., 0.], dtype=np.float32),
    np.array([[0.1], [0.1]], dtype=np.float32),
    np.array([0.], dtype=np.float32)
]




In [43]:
model.set_weights(initialized_weights)

In [44]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [45]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [46]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 3ms/step - loss: 27.9134
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5749
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2570
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.9359
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 26.5789
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 26.2114
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 25.8454
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4754
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0929
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6682
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2577
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8563
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste